[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "silkui"
version = "1.2.2"
description = "UI components for Django — copy, own, customize. Inspired by shadcn/ui."
authors = [
    {name = "Goli Yao Hugues", email = "goliyaohugues@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Django",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "click>=8.0",
    "rich>=13.0",
]

[project.scripts]
silkui = "silkui.cli:main"

[project.urls]
Homepage = "https://github.com/huguescodeur/silkui"
Documentation = "https://silkui-docs.onrender.com"
Issues = "https://github.com/huguescodeur/silkui/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["silkui*"]

[tool.setuptools.package-data]
silkui = ["registry/components/**/*", "registry/base.css"]
